language: java

jdk:
  - openjdk7
  - oraclejdk7

branches:
  only:
    - master
    - develop

install: "mvn --update-snapshots -DskipTests=true install"

before_script: "cp src/main/resources/sample-settings.xml ${HOME}/.m2/settings.xml"

script:
  - sudo ln -s `pwd` /opt/freelib-djatoka
  - etc/init.d/djatoka start
  - test "200" == $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8888/health")
  - mvn djatoka:ingest -Dcsv.file=src/test/resources/id_map.csv
  - etc/inid.d/djatoka stop
  - test "000" == $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8888/health")
  - mvn -Ptravis install

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
